a,b=map(int,input("Enter two Values for Operations : ").split(","))
print("{} + {} = {}".format(a,b,a+b))
print("{} - {} = {}".format(a,b,a-b))
print("{} * {} = {}".format(a,b,a*b))
print("{} / {} = {}".format(a,b,a/b))
print("{} % {} = {}".format(a,b,a%b))
print("{} == {} = {}".format(a,b,a==b))
print("{} < {} = {}".format(a,b,a<b))
print("{} > {} = {}".format(a,b,a>b))
print("{} <= {} = {}".format(a,b,a<=b))
print("{} >= {} = {}".format(a,b,a>=b))
print("{} != {} = {}".format(a,b,a!=b))
print("{} and {} = {}".format(a,b,a and b))
print("{} or {} = {}".format(a,b,a or b))
#print("{} not {} = {}".format(a,b,a not b))
print("{} is {} = {}".format(a,b,a is b))
print("{} is not {} = {}".format(a,b,a is not b))
